server:
  port: 8044
spring:
  profiles: dev
  rabbitmq:
    addresses: amqp://localhost:5672
    username: guest
    password: guest
  cloud:
    stream:
      binders:
        crm:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                username: ${spring.rabbitmq.username}
                password: ${spring.rabbitmq.password}
                addresses: ${spring.rabbitmq.addresses}
                virtual-host: /
      bindings:
        message_output:
          destination: crm_exchange
          group: crm_group
          contentType: text/plain
          producer:
#            exchangeType: topic
            exchangeDurable: true
      rabbit:
        bindings:
          message_output:
            producer:
              exchangeType: topic
              routing-key-expression: '''test444'''