server:
  port: 8044

spring:
  profiles: dev
  rabbitmq:
    addresses: amqp://localhost:5672
    username: guest
    password: guest
  cloud:
     stream:
        binders:
           crm:
               type: rabbit
               environment:
                  spring:
                     rabbitmq:
                         username: ${spring.rabbitmq.username}
                         password: ${spring.rabbitmq.password}
                         addresses: ${spring.rabbitmq.addresses}
                         virtual-host: /crm
        bindings:
           message_output:               #crm生产者
               destination: crm_exchange
               group:   crm_group        #默认情况下同一个队列的只能被同一个group的消费者消费
               contentType: text/plain
               producer:
                   exchangeType: fanout  #主题类型：1.fanout广播模式 2.direct 完全根据key投递 3.topic 根据key进行模糊匹配后投递，可以使用符合#匹配一个或者多个词，*只能匹配一个次
                   exchangeDurable: true #交换机持久化  默认为true