server:
  port: 8046
spring:
  profiles: qa
  rabbitmq: 
    addresses: amqp://localhost:5672
    username: guest
    password: guest
  cloud:
     stream:
        binders:
           crm:
               type: rabbit
               environment:
                  spring:
                     rabbitmq:
                         username: ${spring.rabbitmq.username}
                         password: ${spring.rabbitmq.password}
                         addresses: ${spring.rabbitmq.addresses}
                         virtual-host: /crm
        bindings:
           ecm_shop_template:           #交易系统ECM的货柜模板变更消费者
               binder: crm
               destination: crm_exchange
               group:  crm_group  #默认情况下同一个队列的只能被同一个group的消费者消费
               contentType: text/json
               consumer:
#                   exchangeType: direct  #指定该主题的类型为广播模式
                   autoBindDlq: true
                   republishToDlq: true

