server:
  port: 8045
spring:
  profiles: dev
  rabbitmq: 
    addresses: amqp://localhost:5672
    username: guest
    password: guest
  cloud:
     stream:
        binders:
           crm:
               type: rabbit
               environment:
                  spring:
                     rabbitmq:
                         username: ${spring.rabbitmq.username}
                         password: ${spring.rabbitmq.password}
                         addresses: ${spring.rabbitmq.addresses}
                         virtual-host: /crm
        bindings:
           ecm_shop_template:           #交易系统ECM的货柜模板变更消费者
               binder: crm
               destination: crm_exchange
               group:  crm_group_dev  #默认情况下同一个队列的只能被同一个group的消费者消费
               contentType: text/json
               consumer:
                   exchangeType: fanout  #主题类型：1.fanout广播模式 2.direct 完全根据key投递 3.topic 根据key进行模糊匹配后投递，可以使用符合#匹配一个或者多个词，*只能匹配一个次
                   autoBindDlq: true #设置为true - 绑定器将创建一个DLQ; 您可以选择在deadLetterQueueName中指定一个名称
                   republishToDlq: true

